name: Run Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: hello
      run: bash -c "echo 'hello'"
    - name: sleep
      run: bash -c "sleep 60"
