name: hola

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Run Tests"]
    branches: [main]
    types: 
      - completed
jobs:
  hola:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: hola
      run: bash -c "echo 'hola'"
~                                 
