name: hola

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  workflow_run:
    workflows: ["Run Hello"]
    branches: [main]
    types:
      - completed

jobs:
  hola:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: hola
      run: bash -c "echo 'hola'"
    - name: sleep
      run: bash -c "sleep 60"
~                                 
